import { Problem } from "../models/types.js";

const source = { name: "Yuzhong Chess Keep - beginner puzzle set", url: "https://lichess.org/" };
const problem = (input: Omit<Problem, "source">): Problem => ({ ...input, source });
export const generatedProblems: Problem[] = [
  problem({
    id: "gen-001",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/R7 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 602,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-002",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/1R6 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Rb8#", "Rb8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 604,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-003",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/2R5 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rc8#",
    solutionUci: "c1c8",
    acceptedAnswers: ["Rc8#", "Rc8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 606,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-004",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/3R4 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rd8#",
    solutionUci: "d1d8",
    acceptedAnswers: ["Rd8#", "Rd8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 608,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-005",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/4R3 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Re8#",
    solutionUci: "e1e8",
    acceptedAnswers: ["Re8#", "Re8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 610,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-006",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "5k2/4ppp1/8/8/8/8/6K1/R7 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 612,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-007",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "5k2/4ppp1/8/8/8/8/6K1/1R6 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Rb8#", "Rb8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 614,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-008",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "5k2/4ppp1/8/8/8/8/6K1/2R5 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rc8#",
    solutionUci: "c1c8",
    acceptedAnswers: ["Rc8#", "Rc8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 616,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-009",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "5k2/4ppp1/8/8/8/8/6K1/3R4 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rd8#",
    solutionUci: "d1d8",
    acceptedAnswers: ["Rd8#", "Rd8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 618,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-010",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "5k2/4ppp1/8/8/8/8/6K1/7R w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 620,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-011",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "4k3/3ppp2/8/8/8/8/6K1/R7 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 622,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-012",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "4k3/3ppp2/8/8/8/8/6K1/1R6 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Rb8#", "Rb8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 624,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-013",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "4k3/3ppp2/8/8/8/8/6K1/2R5 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rc8#",
    solutionUci: "c1c8",
    acceptedAnswers: ["Rc8#", "Rc8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 626,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-014",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "4k3/3ppp2/8/8/8/8/6K1/7R w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 628,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-015",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "3k4/2ppp3/8/8/8/8/6K1/R7 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 630,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-016",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "3k4/2ppp3/8/8/8/8/6K1/1R6 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Rb8#", "Rb8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 632,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-017",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "3k4/2ppp3/8/8/8/8/6K1/5R2 w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rf8#",
    solutionUci: "f1f8",
    acceptedAnswers: ["Rf8#", "Rf8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 634,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-018",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "3k4/2ppp3/8/8/8/8/6K1/7R w - - 0 1",
    question: "白车如何利用后排弱点一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["车到第八排横向攻击黑王", "黑王被自己的兵挡住"],
    rating: 636,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-019",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/Q7 w - - 0 1",
    question: "白后如何一步将死？",
    solution: "Qa8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Qa8#", "Qa8"],
    hints: ["皇后控制横线", "走到第八排将杀"],
    rating: 638,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-020",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/1Q6 w - - 0 1",
    question: "白后如何一步将死？",
    solution: "Qb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Qb8#", "Qb8"],
    hints: ["皇后控制横线", "走到第八排将杀"],
    rating: 640,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-021",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/5Q2/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "f2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 642,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-022",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/4Q3/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "e2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 644,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-023",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/3Q4/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "d2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 646,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-024",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/2Q5/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "c2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 648,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-025",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/1Q6/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "b2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 650,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-026",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/6K1/Q7/7k w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg2#",
    solutionUci: "a2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 652,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-027",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/1K6/3Q4/k7 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qe1#",
    solutionUci: "d2e1",
    acceptedAnswers: ["Qe1#", "Qe1"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 654,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-028",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/1K6/4Q3/k7 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qf1#",
    solutionUci: "e2f1",
    acceptedAnswers: ["Qf1#", "Qf1"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 656,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-029",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/1K6/5Q2/k7 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qg1#",
    solutionUci: "f2g1",
    acceptedAnswers: ["Qg1#", "Qg1"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 658,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-030",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/1K6/6Q1/k7 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qh1#",
    solutionUci: "g2h1",
    acceptedAnswers: ["Qh1#", "Qh1"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 660,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-031",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "8/8/8/8/8/1K6/7Q/k7 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qh1#",
    solutionUci: "h2h1",
    acceptedAnswers: ["Qh1#", "Qh1"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 662,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-032",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "7k/5Q2/6K1/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qe8#",
    solutionUci: "f7e8",
    acceptedAnswers: ["Qe8#", "Qe8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 664,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-033",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "7k/4Q3/6K1/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qd8#",
    solutionUci: "e7d8",
    acceptedAnswers: ["Qd8#", "Qd8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 666,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-034",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "7k/3Q4/6K1/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qc8#",
    solutionUci: "d7c8",
    acceptedAnswers: ["Qc8#", "Qc8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 668,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-035",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "7k/2Q5/6K1/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qb8#",
    solutionUci: "c7b8",
    acceptedAnswers: ["Qb8#", "Qb8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 670,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-036",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "7k/1Q6/6K1/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qa8#",
    solutionUci: "b7a8",
    acceptedAnswers: ["Qa8#", "Qa8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 672,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-037",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "k7/3Q4/1K6/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qc8#",
    solutionUci: "d7c8",
    acceptedAnswers: ["Qc8#", "Qc8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 674,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-038",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "k7/4Q3/1K6/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qd8#",
    solutionUci: "e7d8",
    acceptedAnswers: ["Qd8#", "Qd8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 676,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-039",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "k7/5Q2/1K6/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qe8#",
    solutionUci: "f7e8",
    acceptedAnswers: ["Qe8#", "Qe8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 678,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-040",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "皇后与王配合",
    fen: "k7/6Q1/1K6/8/8/8/8/8 w - - 0 1",
    question: "白后如何与白王配合一步将死？",
    solution: "Qf8#",
    solutionUci: "g7f8",
    acceptedAnswers: ["Qf8#", "Qf8"],
    hints: ["白王控制逃跑格", "后贴近黑王将杀"],
    rating: 680,
    themes: ["mateIn1", "queenMate"],
  }),
  problem({
    id: "gen-041",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/2R5 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rc8#",
    solutionUci: "c1c8",
    acceptedAnswers: ["Rc8#", "Rc8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 682,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-042",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/3R4 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rd8#",
    solutionUci: "d1d8",
    acceptedAnswers: ["Rd8#", "Rd8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 684,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-043",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/4R3 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Re8#",
    solutionUci: "e1e8",
    acceptedAnswers: ["Re8#", "Re8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 686,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-044",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/5R2 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rf8#",
    solutionUci: "f1f8",
    acceptedAnswers: ["Rf8#", "Rf8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 688,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-045",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/6R1 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rg8#",
    solutionUci: "g1g8",
    acceptedAnswers: ["Rg8#", "Rg8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 690,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-046",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "k7/8/K7/8/8/8/8/7R w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 692,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-047",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "1k6/8/1K6/8/8/8/8/3R4 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rd8#",
    solutionUci: "d1d8",
    acceptedAnswers: ["Rd8#", "Rd8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 694,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-048",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "1k6/8/1K6/8/8/8/8/4R3 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Re8#",
    solutionUci: "e1e8",
    acceptedAnswers: ["Re8#", "Re8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 696,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-049",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "1k6/8/1K6/8/8/8/8/5R2 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rf8#",
    solutionUci: "f1f8",
    acceptedAnswers: ["Rf8#", "Rf8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 698,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-050",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "1k6/8/1K6/8/8/8/8/6R1 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rg8#",
    solutionUci: "g1g8",
    acceptedAnswers: ["Rg8#", "Rg8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 700,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-051",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "1k6/8/1K6/8/8/8/8/7R w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 702,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-052",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "2k5/8/2K5/8/8/8/8/R7 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 704,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-053",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "2k5/8/2K5/8/8/8/8/4R3 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Re8#",
    solutionUci: "e1e8",
    acceptedAnswers: ["Re8#", "Re8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 706,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-054",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "2k5/8/2K5/8/8/8/8/5R2 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rf8#",
    solutionUci: "f1f8",
    acceptedAnswers: ["Rf8#", "Rf8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 708,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-055",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "2k5/8/2K5/8/8/8/8/6R1 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rg8#",
    solutionUci: "g1g8",
    acceptedAnswers: ["Rg8#", "Rg8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 710,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-056",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "2k5/8/2K5/8/8/8/8/7R w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rh8#",
    solutionUci: "h1h8",
    acceptedAnswers: ["Rh8#", "Rh8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 712,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-057",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "3k4/8/3K4/8/8/8/8/R7 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Ra8#",
    solutionUci: "a1a8",
    acceptedAnswers: ["Ra8#", "Ra8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 714,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-058",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "3k4/8/3K4/8/8/8/8/1R6 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rb8#",
    solutionUci: "b1b8",
    acceptedAnswers: ["Rb8#", "Rb8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 716,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-059",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "3k4/8/3K4/8/8/8/8/5R2 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rf8#",
    solutionUci: "f1f8",
    acceptedAnswers: ["Rf8#", "Rf8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 718,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-060",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "车与王配合",
    fen: "3k4/8/3K4/8/8/8/8/6R1 w - - 0 1",
    question: "白车如何与白王配合一步将死？",
    solution: "Rg8#",
    solutionUci: "g1g8",
    acceptedAnswers: ["Rg8#", "Rg8"],
    hints: ["白车沿直线将杀", "白王控制黑王的逃跑格"],
    rating: 720,
    themes: ["mateIn1", "rookMate"],
  }),
  problem({
    id: "gen-061",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/4n3/8/8/4Q1K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxe5",
    solutionUci: "e2e5",
    acceptedAnswers: ["Qxe5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 722,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-062",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/3n4/8/8/3Q2K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxd5+",
    solutionUci: "d2d5",
    acceptedAnswers: ["Qxd5+", "Qxd5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 724,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-063",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/4b3/4Q3/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护象？",
    solution: "Qxe4",
    solutionUci: "e3e4",
    acceptedAnswers: ["Qxe4"],
    hints: ["寻找黑方无人保护的象", "后直接吃掉它"],
    rating: 726,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-064",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/3b4/3Q4/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护象？",
    solution: "Qxd4",
    solutionUci: "d3d4",
    acceptedAnswers: ["Qxd4"],
    hints: ["寻找黑方无人保护的象", "后直接吃掉它"],
    rating: 728,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-065",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/2r5/8/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护车？",
    solution: "Qxc4+",
    solutionUci: "c2c4",
    acceptedAnswers: ["Qxc4+", "Qxc4"],
    hints: ["寻找黑方无人保护的车", "后直接吃掉它"],
    rating: 730,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-066",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/5r2/8/5QK1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护车？",
    solution: "Qxf4",
    solutionUci: "f2f4",
    acceptedAnswers: ["Qxf4"],
    hints: ["寻找黑方无人保护的车", "后直接吃掉它"],
    rating: 732,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-067",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/6b1/8/6Q1/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护象？",
    solution: "Qxg5+",
    solutionUci: "g3g5",
    acceptedAnswers: ["Qxg5+", "Qxg5"],
    hints: ["寻找黑方无人保护的象", "后直接吃掉它"],
    rating: 734,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-068",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/Qr6/8/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护车？",
    solution: "Qxb4",
    solutionUci: "a4b4",
    acceptedAnswers: ["Qxb4"],
    hints: ["寻找黑方无人保护的车", "后直接吃掉它"],
    rating: 736,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-069",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/6rQ/8/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护车？",
    solution: "Qxg4+",
    solutionUci: "h4g4",
    acceptedAnswers: ["Qxg4+", "Qxg4"],
    hints: ["寻找黑方无人保护的车", "后直接吃掉它"],
    rating: 738,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-070",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/4b3/8/8/8/6K1/4Q3 w - - 0 1",
    question: "白后如何吃掉黑方的无保护象？",
    solution: "Qxe6+",
    solutionUci: "e1e6",
    acceptedAnswers: ["Qxe6+", "Qxe6"],
    hints: ["寻找黑方无人保护的象", "后直接吃掉它"],
    rating: 740,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-071",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/3b4/8/8/8/6K1/3Q4 w - - 0 1",
    question: "白后如何吃掉黑方的无保护象？",
    solution: "Qxd6",
    solutionUci: "d1d6",
    acceptedAnswers: ["Qxd6"],
    hints: ["寻找黑方无人保护的象", "后直接吃掉它"],
    rating: 742,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-072",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R3n3/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxe5",
    solutionUci: "a5e5",
    acceptedAnswers: ["Rxe5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 744,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-073",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R2n4/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxd5",
    solutionUci: "a5d5",
    acceptedAnswers: ["Rxd5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 746,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-074",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R1b5/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxc5",
    solutionUci: "a5c5",
    acceptedAnswers: ["Rxc5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 748,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-075",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R4b2/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxf5",
    solutionUci: "a5f5",
    acceptedAnswers: ["Rxf5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 750,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-076",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R3b3/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxe4",
    solutionUci: "a4e4",
    acceptedAnswers: ["Rxe4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 752,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-077",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R2b4/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxd4",
    solutionUci: "a4d4",
    acceptedAnswers: ["Rxd4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 754,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-078",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R1n5/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxc4",
    solutionUci: "a4c4",
    acceptedAnswers: ["Rxc4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 756,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-079",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R4n2/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxf4",
    solutionUci: "a4f4",
    acceptedAnswers: ["Rxf4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 758,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-080",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/Rb6/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxb4",
    solutionUci: "a4b4",
    acceptedAnswers: ["Rxb4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 760,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-081",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R5b1/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxg4",
    solutionUci: "a4g4",
    acceptedAnswers: ["Rxg4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 762,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-082",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/8/R6n/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxh4+",
    solutionUci: "a4h4",
    acceptedAnswers: ["Rxh4+", "Rxh4"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 764,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-083",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/R3b3/8/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxe6",
    solutionUci: "a6e6",
    acceptedAnswers: ["Rxe6"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 766,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-084",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/R2b4/8/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxd6",
    solutionUci: "a6d6",
    acceptedAnswers: ["Rxd6"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 768,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-085",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/R1n5/8/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxc6",
    solutionUci: "a6c6",
    acceptedAnswers: ["Rxc6"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 770,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-086",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/R4n2/8/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxf6",
    solutionUci: "a6f6",
    acceptedAnswers: ["Rxf6"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 772,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-087",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R6n/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxh5+",
    solutionUci: "a5h5",
    acceptedAnswers: ["Rxh5+", "Rxh5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 774,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-088",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/Rb6/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxb5",
    solutionUci: "a5b5",
    acceptedAnswers: ["Rxb5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 776,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-089",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "车吃无保护子",
    fen: "7k/8/8/R5b1/8/8/6K1/8 w - - 0 1",
    question: "白车如何吃掉黑方的无保护子？",
    solution: "Rxg5",
    solutionUci: "a5g5",
    acceptedAnswers: ["Rxg5"],
    hints: ["寻找横线上无保护的黑子", "车沿横线吃掉"],
    rating: 778,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-090",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/4r3/8/8/6K1/B7 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxe5",
    solutionUci: "a1e5",
    acceptedAnswers: ["Bxe5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 780,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-091",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/3r4/8/5B2/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxd5+",
    solutionUci: "f3d5",
    acceptedAnswers: ["Bxd5+", "Bxd5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 782,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-092",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/4n3/5B2/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxe4",
    solutionUci: "f3e4",
    acceptedAnswers: ["Bxe4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 784,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-093",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/3n4/8/6K1/B7 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxd4",
    solutionUci: "a1d4",
    acceptedAnswers: ["Bxd4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 786,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-094",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/2n5/8/B7/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxc5",
    solutionUci: "a3c5",
    acceptedAnswers: ["Bxc5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 788,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-095",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/5n2/8/7B/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxf5",
    solutionUci: "h3f5",
    acceptedAnswers: ["Bxf5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 790,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-096",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/2r5/8/6K1/5B2 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxc4+",
    solutionUci: "f1c4",
    acceptedAnswers: ["Bxc4+", "Bxc4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 792,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-097",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/5r2/8/6K1/2B5 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxf4",
    solutionUci: "c1f4",
    acceptedAnswers: ["Bxf4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 794,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-098",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/1r6/8/8/6K1/5B2 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxb5",
    solutionUci: "f1b5",
    acceptedAnswers: ["Bxb5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 796,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-099",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/6r1/8/8/6K1/2B5 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxg5",
    solutionUci: "c1g5",
    acceptedAnswers: ["Bxg5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 798,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-100",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/1n6/8/3B2K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxb4",
    solutionUci: "d2b4",
    acceptedAnswers: ["Bxb4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 800,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-101",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/8/6n1/8/4B1K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxg4",
    solutionUci: "e2g4",
    acceptedAnswers: ["Bxg4"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 802,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-102",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/r7/8/8/3B2K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxa5",
    solutionUci: "d2a5",
    acceptedAnswers: ["Bxa5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 804,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-103",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/8/7r/8/8/4B1K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxh5",
    solutionUci: "e2h5",
    acceptedAnswers: ["Bxh5"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 806,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-104",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/4n3/8/8/7B/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxe6+",
    solutionUci: "h3e6",
    acceptedAnswers: ["Bxe6+", "Bxe6"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 808,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-105",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/3n4/8/8/B7/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxd6",
    solutionUci: "a3d6",
    acceptedAnswers: ["Bxd6"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 810,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-106",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/2r5/8/8/5B2/6K1/8 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxc6",
    solutionUci: "f3c6",
    acceptedAnswers: ["Bxc6"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 812,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-107",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "象吃无保护子",
    fen: "6k1/8/5r2/8/8/8/6K1/B7 w - - 0 1",
    question: "白象如何吃掉黑方的无保护子？",
    solution: "Bxf6",
    solutionUci: "a1f6",
    acceptedAnswers: ["Bxf6"],
    hints: ["寻找斜线上无保护的黑子", "象沿斜线吃掉"],
    rating: 814,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-108",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/4q3/8/5N2/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxe5",
    solutionUci: "f3e5",
    acceptedAnswers: ["Nxe5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 816,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-109",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/3r4/8/2N5/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxd5",
    solutionUci: "c3d5",
    acceptedAnswers: ["Nxd5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 818,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-110",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/4r3/2N5/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxe4",
    solutionUci: "c3e4",
    acceptedAnswers: ["Nxe4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 820,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-111",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/3q4/5N2/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxd4",
    solutionUci: "f3d4",
    acceptedAnswers: ["Nxd4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 822,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-112",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/2r5/4N3/8/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxc5",
    solutionUci: "e4c5",
    acceptedAnswers: ["Nxc5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 824,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-113",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/5q2/3N4/8/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxf5",
    solutionUci: "d4f5",
    acceptedAnswers: ["Nxf5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 826,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-114",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/2q5/N7/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxc4",
    solutionUci: "a3c4",
    acceptedAnswers: ["Nxc4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 828,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-115",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/5r2/7N/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxf4",
    solutionUci: "h3f4",
    acceptedAnswers: ["Nxf4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 830,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-116",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/1q6/8/2N5/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxb5",
    solutionUci: "c3b5",
    acceptedAnswers: ["Nxb5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 832,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-117",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/6r1/8/5N2/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxg5",
    solutionUci: "f3g5",
    acceptedAnswers: ["Nxg5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 834,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-118",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/r7/8/1N6/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxa5",
    solutionUci: "b3a5",
    acceptedAnswers: ["Nxa5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 836,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-119",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/7q/8/6N1/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxh5",
    solutionUci: "g3h5",
    acceptedAnswers: ["Nxh5"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 838,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-120",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/q7/2N5/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxa4",
    solutionUci: "c3a4",
    acceptedAnswers: ["Nxa4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 840,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-121",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/8/7r/5N2/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxh4",
    solutionUci: "f3h4",
    acceptedAnswers: ["Nxh4"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 842,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-122",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/4r3/8/3N4/8/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxe6",
    solutionUci: "d4e6",
    acceptedAnswers: ["Nxe6"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 844,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-123",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/3q4/8/4N3/8/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxd6",
    solutionUci: "e4d6",
    acceptedAnswers: ["Nxd6"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 846,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-124",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/5N2/8/4q3/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxe3",
    solutionUci: "f5e3",
    acceptedAnswers: ["Nxe3"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 848,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-125",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "马吃无保护子",
    fen: "6k1/8/8/2N5/8/3r4/6K1/8 w - - 0 1",
    question: "白马如何吃掉黑方的无保护子？",
    solution: "Nxd3",
    solutionUci: "c5d3",
    acceptedAnswers: ["Nxd3"],
    hints: ["马可以跳过其他棋子吃子", "寻找马能攻击到的无保护子"],
    rating: 850,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-126",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "7k/P7/K7/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 852,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-127",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "6k1/2P5/2K5/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "c8=N",
    solutionUci: "c7c8n",
    acceptedAnswers: ["c8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 854,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-128",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "5k2/3P4/3K4/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "d8=N",
    solutionUci: "d7d8n",
    acceptedAnswers: ["d8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 856,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-129",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "2k5/4P3/4K3/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "e8=N",
    solutionUci: "e7e8n",
    acceptedAnswers: ["e8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 858,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-130",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "3k4/5P2/5K2/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "f8=N",
    solutionUci: "f7f8n",
    acceptedAnswers: ["f8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 860,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-131",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "4k3/6P1/6K1/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "g8=N",
    solutionUci: "g7g8n",
    acceptedAnswers: ["g8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 862,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-132",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "1k6/7P/7K/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "h8=N",
    solutionUci: "h7h8n",
    acceptedAnswers: ["h8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 864,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-133",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "6k1/P7/K7/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 866,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-134",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "7k/1P6/1K6/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 868,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-135",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "k7/2P5/2K5/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "c8=N",
    solutionUci: "c7c8n",
    acceptedAnswers: ["c8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 870,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-136",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "1k6/3P4/3K4/8/8/8/8/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "d8=N",
    solutionUci: "d7d8n",
    acceptedAnswers: ["d8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 872,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-137",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1q1k4/8/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 874,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-138",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1r1k4/8/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 876,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-139",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3k4/4q3/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 878,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-140",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3k4/4r3/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 880,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-141",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3k4/8/8/4q3/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 882,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-142",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3k4/8/8/4r3/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 884,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-143",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3q4/8/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 886,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-144",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/3r4/8/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 888,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-145",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1q6/8/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 890,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-146",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1r6/8/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 892,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-147",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/8/4q3/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 894,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-148",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/8/4r3/8/8/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 896,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-149",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/8/8/8/4q3/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 898,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-150",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/8/8/8/4r3/KN1k4 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 900,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-151",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k1q4/8/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 902,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-152",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k1r4/8/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 904,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-153",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k6/4q3/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 906,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-154",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k6/4r3/8/8/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 908,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-155",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k6/8/8/4q3/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 910,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-156",
    gradeBand: "13",
    type: "fork",
    difficulty: 3,
    knowledgePoint: "马叉子",
    fen: "8/8/8/1k6/8/8/4r3/KN6 w - - 0 1",
    question: "白马跳到哪里能将军并同时攻击另一个棋子？",
    solution: "Nc3+",
    solutionUci: "b1c3",
    acceptedAnswers: ["Nc3+", "Nc3"],
    hints: ["骑士可以同时攻击王和另一个棋子", "先将军再吃子"],
    rating: 912,
    themes: ["fork", "check"],
  }),
  problem({
    id: "gen-157",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "综合将杀",
    fen: "8/8/8/8/8/3PK3/2Q5/4k3 w - - 0 1",
    question: "白方一步将死。",
    solution: "Qe2#",
    solutionUci: "c2e2",
    acceptedAnswers: ["Qe2#", "Qe2"],
    hints: ["仔细观察所有白子的攻击范围", "黑王有哪些逃跑格？"],
    rating: 914,
    themes: ["mateIn1"],
  }),
  problem({
    id: "gen-158",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "综合将杀",
    fen: "8/8/8/8/5B2/6K1/5Q2/7k w - - 0 1",
    question: "白方一步将死。",
    solution: "Qg2#",
    solutionUci: "f2g2",
    acceptedAnswers: ["Qg2#", "Qg2"],
    hints: ["仔细观察所有白子的攻击范围", "黑王有哪些逃跑格？"],
    rating: 916,
    themes: ["mateIn1"],
  }),
  problem({
    id: "gen-159",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "综合将杀",
    fen: "8/8/8/8/3B4/2K5/2Q5/k7 w - - 0 1",
    question: "白方一步将死。",
    solution: "Kb4#",
    solutionUci: "c3b4",
    acceptedAnswers: ["Kb4#", "Kb4"],
    hints: ["仔细观察所有白子的攻击范围", "黑王有哪些逃跑格？"],
    rating: 918,
    themes: ["mateIn1"],
  }),
  problem({
    id: "gen-160",
    gradeBand: "14",
    type: "mate_in_1",
    difficulty: 2,
    knowledgePoint: "综合将杀",
    fen: "8/8/8/8/8/5K2/4QR2/6k1 w - - 0 1",
    question: "白方一步将死。",
    solution: "Qf1#",
    solutionUci: "e2f1",
    acceptedAnswers: ["Qf1#", "Qf1"],
    hints: ["仔细观察所有白子的攻击范围", "黑王有哪些逃跑格？"],
    rating: 920,
    themes: ["mateIn1"],
  }),
  problem({
    id: "gen-161",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/n7/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa3",
    solutionUci: "b2a3",
    acceptedAnswers: ["Qxa3"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 922,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-162",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/n7/8/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa4",
    solutionUci: "c2a4",
    acceptedAnswers: ["Qxa4"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 924,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-163",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/n7/8/8/3Q2K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa5",
    solutionUci: "d2a5",
    acceptedAnswers: ["Qxa5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 926,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-164",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/n7/8/8/8/4Q1K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa6",
    solutionUci: "e2a6",
    acceptedAnswers: ["Qxa6"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 928,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-165",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/1n6/Q5K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxb3+",
    solutionUci: "a2b3",
    acceptedAnswers: ["Qxb3+", "Qxb3"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 930,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-166",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/1n6/8/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxb4",
    solutionUci: "b2b4",
    acceptedAnswers: ["Qxb4"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 932,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-167",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/1n6/8/8/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxb5",
    solutionUci: "b2b5",
    acceptedAnswers: ["Qxb5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 934,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-168",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/1n6/8/8/8/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxb6",
    solutionUci: "b2b6",
    acceptedAnswers: ["Qxb6"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 936,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-169",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/2n5/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxc3",
    solutionUci: "b2c3",
    acceptedAnswers: ["Qxc3"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 938,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-170",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "7k/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 940,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-171",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "6k1/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 942,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-172",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "5k2/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 944,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-173",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "2k5/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 946,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-174",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "4k3/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 948,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-175",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "3k4/P7/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 950,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-176",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "8/P6k/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "a8=N",
    solutionUci: "a7a8n",
    acceptedAnswers: ["a8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 952,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-177",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "7k/1P6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 954,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-178",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "6k1/1P6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 956,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-179",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/3Q4 w - - 0 1",
    question: "白后如何一步将死？",
    solution: "Qd8#",
    solutionUci: "d1d8",
    acceptedAnswers: ["Qd8#", "Qd8"],
    hints: ["皇后控制横线", "走到第八排将杀"],
    rating: 958,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-180",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/4Q3 w - - 0 1",
    question: "白后如何一步将死？",
    solution: "Qe8#",
    solutionUci: "e1e8",
    acceptedAnswers: ["Qe8#", "Qe8"],
    hints: ["皇后控制横线", "走到第八排将杀"],
    rating: 960,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-181",
    gradeBand: "15",
    type: "mate_in_1",
    difficulty: 1,
    knowledgePoint: "后排将杀",
    fen: "6k1/5ppp/8/8/8/8/6K1/2Q5 w - - 0 1",
    question: "白后如何一步将死？",
    solution: "Qc8#",
    solutionUci: "c1c8",
    acceptedAnswers: ["Qc8#", "Qc8"],
    hints: ["皇后控制横线", "走到第八排将杀"],
    rating: 962,
    themes: ["mateIn1", "backRankMate"],
  }),
  problem({
    id: "gen-182",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/2n5/8/Q5K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxc4+",
    solutionUci: "a2c4",
    acceptedAnswers: ["Qxc4+", "Qxc4"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 964,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-183",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/2n5/8/8/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxc5",
    solutionUci: "c2c5",
    acceptedAnswers: ["Qxc5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 966,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-184",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/2n5/8/8/8/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxc6",
    solutionUci: "c2c6",
    acceptedAnswers: ["Qxc6"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 968,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-185",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/3n4/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxd3",
    solutionUci: "c2d3",
    acceptedAnswers: ["Qxd3"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 970,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-186",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/3n4/8/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxd4",
    solutionUci: "b2d4",
    acceptedAnswers: ["Qxd4"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 972,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-187",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/3n4/8/8/Q5K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxd5+",
    solutionUci: "a2d5",
    acceptedAnswers: ["Qxd5+", "Qxd5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 974,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-188",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/3n4/8/8/8/3Q2K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxd6",
    solutionUci: "d2d6",
    acceptedAnswers: ["Qxd6"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 976,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-189",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/4n3/3Q2K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxe3",
    solutionUci: "d2e3",
    acceptedAnswers: ["Qxe3"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 978,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-190",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/4n3/8/2Q3K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxe4",
    solutionUci: "c2e4",
    acceptedAnswers: ["Qxe4"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 980,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-191",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/4n3/8/8/1Q4K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxe5",
    solutionUci: "b2e5",
    acceptedAnswers: ["Qxe5"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 982,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-192",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/4n3/8/8/8/Q5K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxe6+",
    solutionUci: "a2e6",
    acceptedAnswers: ["Qxe6+", "Qxe6"],
    hints: ["寻找黑方无人保护的马", "后直接吃掉它"],
    rating: 984,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-193",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "5k2/1P6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 986,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-194",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "4k3/1P6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 988,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-195",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "3k4/1P6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 990,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-196",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "8/1P5k/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 992,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-197",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "8/kP6/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "b8=N",
    solutionUci: "b7b8n",
    acceptedAnswers: ["b8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 994,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-198",
    gradeBand: "14",
    type: "promotion",
    difficulty: 2,
    knowledgePoint: "兵升变",
    fen: "7k/2P5/8/8/8/8/6K1/8 w - - 0 1",
    question: "白兵到达底线应该如何升变？",
    solution: "c8=N",
    solutionUci: "c7c8n",
    acceptedAnswers: ["c8=N"],
    hints: ["兵走到第八排必须升变", "升变为皇后是最强的选择"],
    rating: 996,
    themes: ["promotion"],
  }),
  problem({
    id: "gen-199",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/8/n7/6K1/Q7 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa3",
    solutionUci: "a1a3",
    acceptedAnswers: ["Qxa3"],
    hints: ["黑马没有保护", "后可以直接吃掉"],
    rating: 998,
    themes: ["hangingPiece", "capture"],
  }),
  problem({
    id: "gen-200",
    gradeBand: "13",
    type: "hanging_piece",
    difficulty: 3,
    knowledgePoint: "后吃无保护子",
    fen: "6k1/8/8/8/Q7/n7/6K1/8 w - - 0 1",
    question: "白后如何吃掉黑方的无保护马？",
    solution: "Qxa3",
    solutionUci: "a4a3",
    acceptedAnswers: ["Qxa3"],
    hints: ["黑马没有保护", "后可以直接吃掉"],
    rating: 1000,
    themes: ["hangingPiece", "capture"],
  }),
];